apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: pod1
      image: nicolaka/netshoot:v0.12
      command: ["sleep"]
      args: ["86400"]
      securityContext:
        privileged: false
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - NET_RAW

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: pod2
      image: nicolaka/netshoot:v0.12
      command: ["sleep"]
      args: ["86400"]
      securityContext:
        privileged: false
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - NET_RAW
