apiVersion: v1
kind: Pod
metadata:
  name: netshoot-pod
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: pod1
      image: nicolaka/netshoot:v0.12
      command: ["sleep"]
      args: ["86400"]
      securityContext:
        privileged: false
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - NET_RAW
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - controlplane
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
